version: "2"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - redis
    volumes:
      - .:/app
  redis:
    image: redis:3.2.3-alpine
    volumes:
      - redis:/var/lib/redis/data
volumes:
  redis:
    driver: local
